// Sprite di mondo, sedici pixel per tassello, nella tavolozza comune.
export const CARRO = [
  "................",
  "......gggggg....",
  ".....ghwwwwhg...",
  "....ghhgggghhg..",
  "....gwg.h..gwg..",
  "....gwhhhhhswg..",
  "....gwg.h..gwg..",
  ".....ghwwwwhg...",
  "..gggggggggggg..",
  ".ghwwwwwwwwwwhg.",
  ".ghhghhghhghhhg.",
  ".ghhghhghhghhhg.",
  ".ghwwwwwwwwwwhg.",
  ".ghhghhghhghhhg.",
  ".ghhghhghhghhhg.",
  ".ghwwwwwwwwwwhg.",
  "..ggggggggggggg.",
  "..ghwwwwhg...ggg",
  ".ghhgggghhg...gg",
  ".gwg.h..gwg.....",
  ".gwhhhhhswg.....",
  ".gwg.h..gwg.....",
  "..ghwwwwhg......",
  "...gggggg.......",
];

export const POZZO = [
  "................",
  "...gggggggggg...",
  "..ghwwwwwwwwhg..",
  "...gh..h..hg....",
  "...gh..h..hg....",
  "...gh..s..hg....",
  "...gh..s..hg....",
  "..fff..s..fff...",
  ".feeeffffeeeef..",
  ".fe11222211eef..",
  ".fe12233221eef..",
  ".dfffffffffffd..",
  ".deeeedeeeeeed..",
  ".ddeeeeedeeedd..",
  "..deeedeeeeed...",
  "...ddddddddd....",
];

export const TRONCO = [
  "................",
  "................",
  "................",
  "................",
  "......rr........",
  ".....rhdr.......",
  ".....rhr........",
  ".....rhdrr......",
  ".....rhdhr......",
  ".....rddhr......",
  "....rdhdhdr.....",
  "...rddhhdddr....",
  "..rddhhddhhdr...",
  "...rrrrrrrrr....",
  ".....rr.rr......",
  "................",
];

// I luoghi unici (M7.18.56).
//
// La torre di avvistamento: una garitta di legno su quattro gambe, con la
// scala in mezzo. Alta quasi tre tasselli — si deve vedere da lontano, è il
// posto da cui si guarda — e ancorata ai piedi come tutto il resto.
export const TORRE = [
  "......gggg......",
  ".....ghhhhg.....",
  "....ghwwwwhg....",
  "...ghwwwwwwhg...",
  "..ghwwwwwwwwhg..",
  ".gggggggggggggg.",
  "..ghhhhhhhhhhg..",
  "..ghgrrrrrrghg..",
  "..ghgrrrrrrghg..",
  "..ghhhhhhhhhhg..",
  ".gggggggggggggg.",
  ".ghhhhhhhhhhhhg.",
  "..gh..gwwg..hg..",
  "..gh..g..g..hg..",
  "..gh..gwwg..hg..",
  "..gh..g..g..hg..",
  "..gh..gwwg..hg..",
  "..gh..g..g..hg..",
  "..gh..gwwg..hg..",
  "..gh..g..g..hg..",
  "..ghhhhhhhhhhg..",
  "..gh..g..g..hg..",
  "..gh..gwwg..hg..",
  "..gh..g..g..hg..",
  "..gh..gwwg..hg..",
  "..gh..g..g..hg..",
  "..gh..gwwg..hg..",
  "..gh..g..g..hg..",
  "..gh..gwwg..hg..",
  "..ghhhhhhhhhhg..",
  "..gh..gwwg..hg..",
  "..gh..g..g..hg..",
  "..gh..gwwg..hg..",
  "..gh..g..g..hg..",
  "..gh..gwwg..hg..",
  "..gh..g..g..hg..",
  "..gh..gwwg..hg..",
  "..gh..g..g..hg..",
  ".ggg..g..g..ggg.",
  "gggg..gggg..gggg",
];

// La parete della cava: roccia a blocchi irregolari, luce in alto a
// sinistra. Non è un muro — non ci sono file — ed è la cosa che si spacca col
// piccone e torna a ogni stagione.
export const PARETE_CAVA = [
  "....YX....YY....",
  "..YYeXY..YeeYX..",
  ".YeeeXfYYeeeXYY.",
  "YeeeeXfeeeeXYeeY",
  "eeeedXXeeedXfeee",
  "eeeXXYXXXXXYeeee",
  "eXXYYeeYYXXXeeee",
  "XYYeeeeeXYYXXXed",
  "XeeeeeeeXfeeYXXX",
  "XXXeeeedXfeeeeXY",
  "eYXXeedXYeeeeXYe",
  "eeeXXXXXXeeeeXfe",
  "eeeeXYYeXXXeXYee",
  "eeeeXfeeeYXXXXXe",
  "eeeXYeeeeeXYYYXX",
  "eXXXXeeeeXXfeeeY",
  "XYYYXXXXXYXXeeee",
  "YeeeeYXYYeeXXeed",
  "eeeeeeXfeeeeXXdd",
  "XXXXXXXXXXXXXXXX",
];

// La macina del mulino (M7.18.57): due mole di pietra su un telaio di legno,
// con il manico in cima.
export const MACINA = [
  "................",
  "................",
  "................",
  "................",
  "......gwwg......",
  "......ghhg......",
  "...XXXXXXXXXX...",
  "..XYYYYYYYYYYX..",
  "..XfffffffffeX..",
  "..XeeeeeeeeedX..",
  "...XXXXXXXXXX...",
  "..XXXXXXXXXXXX..",
  ".XYYYYYYYYYYYYX.",
  ".XffffffffffffX.",
  ".XeeeeeeeeeeedX.",
  ".XddddddddddddX.",
  "..XXXXXXXXXXXX..",
  "..gwwwwwwwwwwg..",
  "..ghhhhhhhhhhg..",
  "..gg........gg..",
];

// La campana della chiesa (M7.18.57): bronzo sotto un'incastellatura di
// legno, con il battaglio.
export const CAMPANA = [
  ".gggggggggggggg.",
  ".gwwwwwwwwwwwwg.",
  ".ghhhhhhhhhhhhg.",
  ".gg....KK....gg.",
  ".gh...KMMK...hg.",
  ".gh..KMNNNK..hg.",
  ".gh..KMNNNK..hg.",
  ".gh.KMNNNNNK.hg.",
  ".gh.KMNNNNNK.hg.",
  ".gh.KMNNNNNK.hg.",
  ".ghKMNNNNNNNKhg.",
  ".ghKKKKKKKKKKhg.",
  ".gh....KK....hg.",
  ".gh....KK....hg.",
  ".gh..........hg.",
  ".gh..........hg.",
  ".gh..........hg.",
  ".gh..........hg.",
  ".gh..........hg.",
  ".gh..........hg.",
  ".gh..........hg.",
  ".gh..........hg.",
  ".ggg........ggg.",
  "gggg........gggg",
];

// La ruota del mulino (M7.18.60.1): di legno, a raggi, incastrata nel muro
// di fianco. Solo decorativa.
export const RUOTA = [
  "................",
  "................",
  "................",
  "................",
  ".....gggggg.....",
  "...gggNNNNggg...",
  "..ggNNNwwNNNgg..",
  ".ggNNKKwwKKNNgg.",
  ".gNNwKKKKKKwNNg.",
  "ggNKKwKKKKwKKNgg",
  "gNNKKKwggwKKKNNg",
  "gNwwKKghhgKKwwNg",
  "gNwwKKghhgKKwwNg",
  "gNNKKKwggwKKKNNg",
  "ggNKKwKKKKwKKNgg",
  ".gNNwKKKKKKwNNg.",
  ".ggNNKKwwKKNNgg.",
  "..ggNNNwwNNNgg..",
  "...gggNNNNggg...",
  ".....gggggg.....",
];
