// Sprite di mondo, sedici pixel per tassello, nella tavolozza comune.
export const CARRO = [
  "................",
  "......gggggg....",
  ".....ghwwwwhg...",
  "....ghhgggghhg..",
  "....gwg.h..gwg..",
  "....gwhhhhhswg..",
  "....gwg.h..gwg..",
  ".....ghwwwwhg...",
  "..gggggggggggg..",
  ".ghwwwwwwwwwwhg.",
  ".ghhghhghhghhhg.",
  ".ghhghhghhghhhg.",
  ".ghwwwwwwwwwwhg.",
  ".ghhghhghhghhhg.",
  ".ghhghhghhghhhg.",
  ".ghwwwwwwwwwwhg.",
  "..ggggggggggggg.",
  "..ghwwwwhg...ggg",
  ".ghhgggghhg...gg",
  ".gwg.h..gwg.....",
  ".gwhhhhhswg.....",
  ".gwg.h..gwg.....",
  "..ghwwwwhg......",
  "...gggggg.......",
];

export const POZZO = [
  "................",
  "...gggggggggg...",
  "..ghwwwwwwwwhg..",
  "...gh..h..hg....",
  "...gh..h..hg....",
  "...gh..s..hg....",
  "...gh..s..hg....",
  "..fff..s..fff...",
  ".feeeffffeeeef..",
  ".fe11222211eef..",
  ".fe12233221eef..",
  ".dfffffffffffd..",
  ".deeeedeeeeeed..",
  ".ddeeeeedeeedd..",
  "..deeedeeeeed...",
  "...ddddddddd....",
];

export const TRONCO = [
  "................",
  "................",
  "................",
  "................",
  "......rr........",
  ".....rhdr.......",
  ".....rhr........",
  ".....rhdrr......",
  ".....rhdhr......",
  ".....rddhr......",
  "....rdhdhdr.....",
  "...rddhhdddr....",
  "..rddhhddhhdr...",
  "...rrrrrrrrr....",
  ".....rr.rr......",
  "................",
];
